- name: Configure web servers
  hosts: web
  become: true
  tasks:
    - name: update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: install nginx
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: create index.html
      copy:
        dest: /var/www/html/index.html
        content: |
          <h1>Deployed by Jenkins + Terraform + Ansible</h1>
          <p>Host: {{ inventory_hostname }}</p>

    - name: ensure nginx started
      service:
        name: nginx
        state: started
        enabled: yes
